<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260729105052 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total_price NUMERIC(10, 0) NOT NULL, status VARCHAR(40) NOT NULL, owmer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDEF8A81357 ON booking (owmer_id)');
        $this->addSql('CREATE TABLE screening (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price NUMERIC(5, 0) NOT NULL, status VARCHAR(100) NOT NULL, movie_id INT DEFAULT NULL, hall_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B708297D8F93B6FC ON screening (movie_id)');
        $this->addSql('CREATE INDEX IDX_B708297D52AFCFD6 ON screening (hall_id)');
        $this->addSql('CREATE TABLE seat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, row_number INT NOT NULL, seat_number INT NOT NULL, seat_type VARCHAR(50) NOT NULL, hall_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3D5C366652AFCFD6 ON seat (hall_id)');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prise NUMERIC(10, 2) NOT NULL, status VARCHAR(50) NOT NULL, booking_id INT NOT NULL, screening_id INT NOT NULL, seat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA33301C60 ON ticket (booking_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA370F5295D ON ticket (screening_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3C1DAFE35 ON ticket (seat_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEF8A81357 FOREIGN KEY (owmer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE screening ADD CONSTRAINT FK_B708297D8F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id)');
        $this->addSql('ALTER TABLE screening ADD CONSTRAINT FK_B708297D52AFCFD6 FOREIGN KEY (hall_id) REFERENCES hall (id)');
        $this->addSql('ALTER TABLE seat ADD CONSTRAINT FK_3D5C366652AFCFD6 FOREIGN KEY (hall_id) REFERENCES hall (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA33301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA370F5295D FOREIGN KEY (screening_id) REFERENCES screening (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3C1DAFE35 FOREIGN KEY (seat_id) REFERENCES seat (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hall ADD type VARCHAR(50) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEF8A81357');
        $this->addSql('ALTER TABLE screening DROP CONSTRAINT FK_B708297D8F93B6FC');
        $this->addSql('ALTER TABLE screening DROP CONSTRAINT FK_B708297D52AFCFD6');
        $this->addSql('ALTER TABLE seat DROP CONSTRAINT FK_3D5C366652AFCFD6');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA33301C60');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA370F5295D');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3C1DAFE35');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE screening');
        $this->addSql('DROP TABLE seat');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE hall DROP type');
    }
}
